Agharta/eip145 bitwise shift
etclabscore/go-ethereum pull request #15
Opened 2019-07-29 17:44 UTC by dziabko

Implemented EIP 145 (SAR, SHR, SHL opcodes). Implemented instruction_test.go file for basic tests. Added IsAghartha check.

2019-07-29 18:04 UTC, austinabell requested changes

2019-07-29 18:04 UTC, austinabell commented on tests/util.go
> +type ShiftTest struct {
Not used?

2019-07-29 18:04 UTC, austinabell commented on tests/init.go
> +		ExplosionBlock:           big.NewInt(0),
Not needed to define ExplosionBlock

2019-08-02 07:49 UTC, soc1c commented
changed base to `development`, waiting for reapplication of #5 and #7

2019-08-19 15:51 UTC, austinabell requested changes
Please be careful when and where you rebase and changes that are introduced

2019-08-19 15:51 UTC, austinabell commented on core/vm/gas.go
>  	RETURNDATASIZE: {0, GasQuickStep, 1},
fmt if possible

2019-08-19 15:51 UTC, austinabell commented on core/execution.go
> +		env.Db().SetNonce(*address, 1)
Reintrocuces nonce bug, do starting nonce + 1.

2019-08-19 15:51 UTC, austinabell commented on core/vm/instructions.go
> +func opCreate2(pc *uint64, env Environment, contract *Contract, memory *Memory, stack *stack) ([]byte, error) {
Why is Create2 being introduced with bitwise shift?

2019-08-19 15:51 UTC, austinabell commented on core/vm/runtime/env.go
> +func (self *Env) Create2(caller vm.ContractRef, data []byte, gas, price, salt, value *big.Int) ([]byte, common.Address, error) {
same as above

2019-08-19 15:51 UTC, austinabell commented on core/vm/vm.go
> +	case CREATE2:
same as above

2019-08-19 15:51 UTC, austinabell commented on core/vm_env.go
> +func (self *VMEnv) Create2(me vm.ContractRef, data []byte, gas, price, salt, value *big.Int) ([]byte, common.Address, error) {
same as above

2019-08-19 15:51 UTC, austinabell commented on crypto/crypto.go
> +func CreateAddress2(b common.Address, salt []byte, inithash []byte) common.Address {
same as above

2019-08-19 15:51 UTC, austinabell commented on tests/state_test.go
> +	// EIP 684 Implementations
The following test skips should not be reintroduced or added (All of them)

2019-08-19 15:51 UTC, austinabell commented on tests/state_test.go
> +		// "ConstantinopleFix":            true,
Remove the commented out line if you don't plan to add it back after this

2019-08-19 15:51 UTC, austinabell commented on tests/util.go
> +func (self *Env) Create2(caller vm.ContractRef, data []byte, gas, price, salt, value *big.Int) ([]byte, common.Address, error) {
Remove this in the context of this PR

2019-08-19 15:51 UTC, austinabell commented on core/execution.go
> +	errCodeStoreOutOfGas        = errors.New("contract creation code storage out of gas")
Not relevant to your changes?

2019-08-19 15:51 UTC, austinabell commented on cmd/evm/main.go
> +func (self *VMEnv) Create2(caller vm.ContractRef, data []byte, gas, price, salt, value *big.Int) ([]byte, common.Address, error) {
This is bitwise shift PR?

2019-08-19 15:51 UTC, austinabell commented on core/execution.go
> +	nonce := env.Db().GetNonce(caller.Address())
Should not be changing the logic of Create, the previous changes were done to fix bugs within a simulated environment

2019-08-19 15:51 UTC, austinabell commented on core/execution.go
> +func exec(env vm.Environment, caller vm.ContractRef, codeAddr *common.Address, codeHash common.Hash, input, code []byte, gas, gasPrice, value *big.Int, readOnly bool) (ret []byte, addr common.Address
this isn't being used from what I can see?

2019-09-20 00:20 UTC, GregTheGreek submitted a review, later dismissed

2019-09-20 01:21 UTC, austinabell commented
This PR isn't ready, requires CREATE2 in first and be rebased for tests/ agharta config

2019-09-25 15:00 UTC, closed without merging